version: '3.7'

services:
  tempo:
    image: grafana/tempo:latest
    networks:
      - infra
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    networks:
      - infra
    volumes:
      - ./otelcol/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver

  mimir:
    image: grafana/mimir:2.17.1
    networks:
      - infra
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir/mimir.yaml
    command: "--config.file=/etc/mimir/mimir.yaml"

  grafana:
    image: grafana/grafana:12.2.0
    networks:
      - infra
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  loki:
    image: grafana/loki:3.2.0
    networks:
      - infra
    volumes:
      - ./loki/config.yaml:/mnt/config/loki.yml
    command: --config.file=/mnt/config/loki.yml

networks:
  infra:
    external: true
    name: local-infra

volumes:
  grafana_data:
